export const options = {
	audio: {
		beep: [true, false],
		beepSrc: [
			'/qwerty-learner/public/sounds/key-sound/Alpacas.mp3',
			'/qwerty-learner/public/sounds/key-sound/Buckling Spring.mp3',
			'/qwerty-learner/public/sounds/key-sound/Cherry MX Blacks.mp3',
			'/qwerty-learner/public/sounds/key-sound/Cherry MX Blues.mp3',
			'/qwerty-learner/public/sounds/key-sound/Cherry MX Browns.mp3',
			'/qwerty-learner/public/sounds/key-sound/Gateron Black Inks.mp3',
			'/qwerty-learner/public/sounds/key-sound/Gateron Red Inks.mp3',
			'/qwerty-learner/public/sounds/key-sound/Holy Pandas.mp3',
			'/qwerty-learner/public/sounds/key-sound/Kailh Box Navies.mp3',
			'/qwerty-learner/public/sounds/key-sound/NovelKeys Creams.mp3',
			'/qwerty-learner/public/sounds/key-sound/SKCM Blue Alps.mp3',
			'/qwerty-learner/public/sounds/key-sound/Topre.mp3',
			'/qwerty-learner/public/sounds/key-sound/Turquoise Tealios.mp3'
		]
	},
	dict: {
		shuffle: [true, false],
		dictSrc: [
			'/qwerty-learner/public/dicts/4000_Essential_English_Words-meaning.json',
			'/qwerty-learner/public/dicts/4000_Essential_English_Words-sentence.json',
			'/qwerty-learner/public/dicts/archVocabulary.json',
			'/qwerty-learner/public/dicts/BEC_2_T.json',
			'/qwerty-learner/public/dicts/BEC_3_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_1_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_2_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_3_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_4_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_5_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_6_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_7_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_8_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_9_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_10_T.json',
			'/qwerty-learner/public/dicts/BeiShiGaoZhong_11_T.json',
			'/qwerty-learner/public/dicts/CET4_T.json',
			'/qwerty-learner/public/dicts/CET6_T.json',
			'/qwerty-learner/public/dicts/Child_c++.json',
			'/qwerty-learner/public/dicts/Child_python_code.json',
			'/qwerty-learner/public/dicts/Child_python_turtle_code.json',
			'/qwerty-learner/public/dicts/chinese_test.json',
			'/qwerty-learner/public/dicts/ChuZhongluan_2_T.json',
			'/qwerty-learner/public/dicts/coca20000.json',
			'/qwerty-learner/public/dicts/csharp-list.json',
			'/qwerty-learner/public/dicts/DanCiDeJianFa_4.json',
			'/qwerty-learner/public/dicts/DanCiDeJianFa_6.json',
			'/qwerty-learner/public/dicts/DanCiDeMimi_1.json',
			'/qwerty-learner/public/dicts/DanCiDeMimi_2.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_1.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_2.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_3.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_4.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_5.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_6.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_7.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_8.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_9.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_10.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_11.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_12.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_13.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_14.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_15.json',
			'/qwerty-learner/public/dicts/EF_LEVEL_16.json',
			'/qwerty-learner/public/dicts/en2german.json',
			'/qwerty-learner/public/dicts/GaoKao_3500.json',
			'/qwerty-learner/public/dicts/GaoKaoZhenTiHeXinGaoPin.json',
			'/qwerty-learner/public/dicts/GaoZhongluan_2_T.json',
			'/qwerty-learner/public/dicts/german2en.json',
			'/qwerty-learner/public/dicts/GMAT_3_T.json',
			'/qwerty-learner/public/dicts/GRE_3_T.json',
			'/qwerty-learner/public/dicts/IELTS_3_T.json',
			'/qwerty-learner/public/dicts/IELTS_WANG_3.json',
			'/qwerty-learner/public/dicts/IELTS_WANG_4.json',
			'/qwerty-learner/public/dicts/IELTS_WANG_5.json',
			'/qwerty-learner/public/dicts/IELTS_WANG_11.json',
			'/qwerty-learner/public/dicts/it-words.json',
			'/qwerty-learner/public/dicts/itVocabulary.json',
			'/qwerty-learner/public/dicts/Jap_High-Frequency_N1.json',
			'/qwerty-learner/public/dicts/Jap_High-Frequency_N2.json',
			'/qwerty-learner/public/dicts/Jap_High-Frequency_N3.json',
			'/qwerty-learner/public/dicts/Jap_High-Frequency_N4N5.json',
			'/qwerty-learner/public/dicts/japanese_test.json',
			'/qwerty-learner/public/dicts/Japanesebasicword.json',
			'/qwerty-learner/public/dicts/JapVocabList.N1.json',
			'/qwerty-learner/public/dicts/JapVocabList.N2.json',
			'/qwerty-learner/public/dicts/JapVocabList.N3.json',
			'/qwerty-learner/public/dicts/JapVocabList.N4.json',
			'/qwerty-learner/public/dicts/JapVocabList.N5.json',
			'/qwerty-learner/public/dicts/java-arraylist.json',
			'/qwerty-learner/public/dicts/java-character.json',
			'/qwerty-learner/public/dicts/java-hashmap.json',
			'/qwerty-learner/public/dicts/java-linkedlist.json',
			'/qwerty-learner/public/dicts/java-string.json',
			'/qwerty-learner/public/dicts/java-stringBuffer.json',
			'/qwerty-learner/public/dicts/js-array.json',
			'/qwerty-learner/public/dicts/js-date.json',
			'/qwerty-learner/public/dicts/js-global.json',
			'/qwerty-learner/public/dicts/js-map-set.json',
			'/qwerty-learner/public/dicts/js-math.json',
			'/qwerty-learner/public/dicts/js-number.json',
			'/qwerty-learner/public/dicts/js-object.json',
			'/qwerty-learner/public/dicts/js-promise.json',
			'/qwerty-learner/public/dicts/js-string.json',
			'/qwerty-learner/public/dicts/KaoYan_3_T.json',
			'/qwerty-learner/public/dicts/KaoYan_2024.json',
			'/qwerty-learner/public/dicts/KaoYanShanGuo_2023.json',
			'/qwerty-learner/public/dicts/Level4luan_2_T.json',
			'/qwerty-learner/public/dicts/Level8luan_2_T.json',
			'/qwerty-learner/public/dicts/linux-command.json',
			'/qwerty-learner/public/dicts/NCE_1.json',
			'/qwerty-learner/public/dicts/NCE_2.json',
			'/qwerty-learner/public/dicts/NCE_3.json',
			'/qwerty-learner/public/dicts/NCE_4.json',
			'/qwerty-learner/public/dicts/Node-fs.json',
			'/qwerty-learner/public/dicts/Node-path.json',
			'/qwerty-learner/public/dicts/OxfordVocabulary_juniorMiddleSH.json',
			'/qwerty-learner/public/dicts/PEPChuZhong7_1_T.json',
			'/qwerty-learner/public/dicts/PEPChuZhong7_2_T.json',
			'/qwerty-learner/public/dicts/PEPChuZhong8_1_T.json',
			'/qwerty-learner/public/dicts/PEPChuZhong8_2_T.json',
			'/qwerty-learner/public/dicts/PEPChuZhong9_1_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_1_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_2_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_3_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_4_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_5_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_6_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_7_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_8_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_9_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_10_T.json',
			'/qwerty-learner/public/dicts/PEPGaoZhong_11_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue3_1_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue3_2_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue4_1_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue4_2_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue5_1_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue5_2_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue6_1_T.json',
			'/qwerty-learner/public/dicts/PEPXiaoXue6_2_T.json',
			'/qwerty-learner/public/dicts/PETS_3.json',
			'/qwerty-learner/public/dicts/PETS3-2023.json',
			'/qwerty-learner/public/dicts/PTE_FIB_L.json',
			'/qwerty-learner/public/dicts/PTE_FIB_R_junior.json',
			'/qwerty-learner/public/dicts/PTE_FIB_R_senior.json',
			'/qwerty-learner/public/dicts/PTE_junior.json',
			'/qwerty-learner/public/dicts/PTE_senior.json',
			'/qwerty-learner/public/dicts/PTE_WFD.json',
			'/qwerty-learner/public/dicts/python-array.json',
			'/qwerty-learner/public/dicts/python-builtin.json',
			'/qwerty-learner/public/dicts/python-class.json',
			'/qwerty-learner/public/dicts/python-date.json',
			'/qwerty-learner/public/dicts/python-file.json',
			'/qwerty-learner/public/dicts/python-math.json',
			'/qwerty-learner/public/dicts/python-set.json',
			'/qwerty-learner/public/dicts/python-string.json',
			'/qwerty-learner/public/dicts/python-sys.json',
			'/qwerty-learner/public/dicts/SAT_3_T.json',
			'/qwerty-learner/public/dicts/SATen.json',
			'/qwerty-learner/public/dicts/SQL_statement_lower-case.json',
			'/qwerty-learner/public/dicts/SQL_statement_upper-case.json',
			'/qwerty-learner/public/dicts/suffix_word.json',
			'/qwerty-learner/public/dicts/TOEFL_3_T.json',
			'/qwerty-learner/public/dicts/Top50Prepositions.json',
			'/qwerty-learner/public/dicts/Top60Pronouns.json',
			'/qwerty-learner/public/dicts/Top250AdverbWords.json',
			'/qwerty-learner/public/dicts/Top500AdjectiveWords.json',
			'/qwerty-learner/public/dicts/Top1000VerbWords.json',
			'/qwerty-learner/public/dicts/Top1500NounWords.json',
			'/qwerty-learner/public/dicts/top2000words.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_1_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_2_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_3_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_4_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_5_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheChuZhong_6_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheGaoZhong_1_T.json',
			'/qwerty-learner/public/dicts/WaiYanSheGaoZhong_2_T.json',
			'/qwerty-learner/public/dicts/word_roots1.json',
			'/qwerty-learner/public/dicts/ZhongKaoHeXin.json'
		]
	},
	input: {
		ignoreCase: [true, false]
	},
	load: [true, false]
};

export default {
	audio: {
		beep: options.audio.beep[0],
		beepSrc: options.audio.beepSrc[0]
	},
	dict: {
		shuffle: options.dict.shuffle[0],
		dictSrc: options.dict.dictSrc[0]
	},
	input: {
		ignoreCase: options.input.ignoreCase[0]
	},
	load: false
};
